stages:
  featurization:
    cmd: python src/featurization.py
    deps:
    - data/AirQualityUCI.xlsx
    - src/constants.py
    - src/featurization.py
    outs:
    - data/processed_train_lookback.npy:
        persist: true
    - data/processed_train_prediction.npy:
        persist: true
    - data/processed_validation_lookback.npy:
        persist: true
    - data/processed_validation_prediction.npy:
        persist: true
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/processed_train_lookback.npy
    - data/processed_train_prediction.npy
    - data/processed_validation_lookback.npy
    - data/processed_validation_prediction.npy
    - src/arch.py
    - src/constants.py
    - src/data_prep.py
    - src/train_model.py
    outs:
    - data/model.pkl:
        persist: true
    - params.yml:
        cache: false
    metrics:
    - model.csv:
        cache: false
