stages:
  featurization:
    cmd: python code/featurization.py
    deps:
    - code/featurization.py
    - data/test_data.xlsx
    - data/train_data.xlsx
    outs:
    - data/norm_params.json
    - data/processed_test_data.npy
    - data/processed_train_data.npy
  training:
    cmd: python code/train_model.py
    deps:
    - code/train_model.py
    - data/processed_train_data.npy
    outs:
    - data/model.pkl
    metrics:
    - metrics/train_metric.json:
        cache: false
