stages:
  featurization:
    cmd: python code/featurization.py
    deps:
    - code/featurization.py
    - data/data.xlsx
    outs:
    - data/norm_params.json
    - data/processed_train_lookback.npy
    - data/processed_train_prediction.npy
    - data/processed_validation_lookback.npy
    - data/processed_validation_prediction.npy
  training:
    cmd: python code/train_model.py
    deps:
    - code/train_model.py
    - data/processed_train_data.npy
    outs:
    - data/model.pkl
    metrics:
    - metrics/train_metric.json:
        cache: false
  eval:
    cmd: python code/eval.py
    deps:
    - code/eval.py
    - data/model.pkl
    - data/processed_test_data.npy
    metrics:
    - metrics/eval.json:
        cache: false
